import { v7 as uuidv7 } from "uuid";

/**
 * Generates a UUIDv7 identifier.
 * All IDs in the system MUST be generated by this function.
 * UUIDv7 embeds a timestamp, giving us transaction time ordering.
 */
export function generateId(): string {
  return uuidv7();
}
